### PR TITLE
#135 Move dev done in CFOS-95 to images component

### PR DESCRIPTION
**Pull request by Salam-Dalloul**

### CODE REVIEW

**Comment by afonsobspinto** [comment]
If you agree, I will delay my review until https://github.com/MetaCell/cfos-visualizer/pull/56 gets merged

**Comment by Salam-Dalloul** [comment]
> If you agree, I will delay my review until #56 gets merged

@afonsobspinto  this actually has to be reviewed first, as it only have @enicolasgomez code which i only moved to the images tab, after merging this one, #56 depends on it, which includes the styling fixes for the component where i have changed it's data structure to meet the tree-view criteria, along with adding some other styling to meet the figma one

**Review by afonsobspinto — CHANGES_REQUESTED** [review]
Even though I understand that this was the implementation you were given, I would prefer to merge the PR only after we replace the atlas name with the experiment name as we discussed in the last meeting:

image

The rest looks good to me

**Review by afonsobspinto — APPROVED** [review]
Looks good to me.

Upon merge we should update the index.json in the bucket with the new format since the change is not backwards compatible. cc @ddelpiano

**Pull request merged**
